#!/usr/bin/env python3
"""Generate README.md from data/modules.yaml.

Usage:
    python3 scripts/generate_readme.py          # write README.md
    python3 scripts/generate_readme.py --check  # exit 1 if README.md is stale
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent

REPO = "landscape82/awesome-eurorack-modular-resources"

CORE_BADGES = (
    f"[![Awesome](https://awesome.re/badge.svg)](https://awesome.re) "
    f"[![Validate](https://github.com/{REPO}/actions/workflows/validate.yml/badge.svg)]"
    f"(https://github.com/{REPO}/actions/workflows/validate.yml) "
    f"[![Lint](https://github.com/{REPO}/actions/workflows/lint.yml/badge.svg)]"
    f"(https://github.com/{REPO}/actions/workflows/lint.yml) "
    f"[![Link Check](https://github.com/{REPO}/actions/workflows/link-check.yml/badge.svg)]"
    f"(https://github.com/{REPO}/actions/workflows/link-check.yml)"
)

EXTRA_BADGES = (
    f"[![Broken Links](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/{REPO}/main/.github/badges/broken-links.json)]"
    f"(https://github.com/{REPO}/actions/workflows/link-check.yml) "
    f"[![Catalogue Entries](https://img.shields.io/endpoint?url=https://raw.githubusercontent.com/{REPO}/main/.github/badges/entries.json)]"
    f"(data/modules.yaml) "
    f"[![Dependabot](https://img.shields.io/github/issues-search/{REPO}?query=is%3Apr+is%3Aopen+label%3Adependencies&label=dependabot)]"
    f"(https://github.com/{REPO}/pulls?q=is%3Apr+is%3Aopen+label%3Adependencies)"
)

BADGES = f"{CORE_BADGES}\n\n{EXTRA_BADGES}"

HEADER = f"""{BADGES}

# 🎛️ Awesome Eurorack Code

A curated index of open-source Eurorack firmware, hardware, SDKs and programmable platforms.

Information here is fragmented no more: every entry below is generated from
[`data/modules.yaml`](data/modules.yaml), the single source of truth. To add or
correct an entry, edit that file — see [CONTRIBUTING.md](CONTRIBUTING.md) — and
this table will be regenerated by CI.

**Legend:** 🔧 firmware · 🔩 hardware · 📦 SDK · 💻 platform · ✅ available · — not applicable / not published
Status is self-reported by each entry's maintainers where available.

## 🗂️ Catalogue
"""

FOOTER = """
See [docs/schema.md](docs/schema.md) for the full metadata model and
[docs/structure.md](docs/structure.md) for the repository layout.

## 🔗 Related Lists

- **[Awesome Sound Design resources](https://github.com/landscape82/awesome-sound-design-resources)** - Curated list of resources and tools for audio synthesis, production, and sound design.

## License

[MIT](LICENSE) for the catalogue metadata, documentation, and tooling in this
repository. Individual projects listed in the catalogue keep their own
licenses — see each entry's repository link.
"""


def yn(v) -> str:
    return "✅" if v else "—"


def build_table(modules: list[dict]) -> str:
    rows = [
        "| Manufacturer | Module | 🔧 Firmware | 🔩 Hardware | 📦 SDK | 💻 Platform | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for m in sorted(modules, key=lambda x: (x["manufacturer"], x["module"])):
        types = set(m.get("type", []))
        cpu = ", ".join(m.get("platform", {}).get("cpu", [])) or "—"
        maintained = m.get("status", {}).get("maintained")
        status = "✅" if maintained is True else maintained or "—"
        rows.append(
            "| {manufacturer} | [{module}]({repo}) | {fw} | {hw} | {sdk} | {cpu} | {status} |".format(
                manufacturer=m["manufacturer"],
                module=m["module"],
                repo=m["repository"],
                fw=yn("firmware" in types or "alternative-firmware" in types),
                hw=yn("hardware" in types),
                sdk=yn("sdk" in types),
                cpu=cpu,
                status=status,
            )
        )
    return "\n".join(rows) + "\n"


def render() -> str:
    data = yaml.safe_load((ROOT / "data" / "modules.yaml").read_text())
    return HEADER + "\n" + build_table(data.get("modules", [])) + FOOTER


def main() -> int:
    content = render()
    readme = ROOT / "README.md"

    if "--check" in sys.argv:
        current = readme.read_text() if readme.exists() else ""
        if current != content:
            print("README.md is stale — run scripts/generate_readme.py and commit the result.")
            return 1
        print("README.md is up to date.")
        return 0

    readme.write_text(content)
    print(f"Wrote {readme}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
